/**********************************************************************************************************************
 * \file Scheduling_Ex.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "IfxStm.h"
#include "IfxScuCcu.h"
#include "ADC_Background_Ex.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* Define priorities for the ISR */
#define IFX_INTPRIO_STM0_SR0  10

#define STM_TIME_1MS    100000U

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* Declare STM variables */
Ifx_STM *stmSfr;
IfxStm_CompareConfig stmConfig;


/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
/* variables */
uint32 taskCounter = 0;
uint8 task1msFlag, task10msFlag, task100msFlag, task1sFlag = 0;
//Add ADC variables

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void init_stm0(void);
void core0_task(void);
void core0_task_1ms(void);
void core0_task_10ms(void);
void core0_task_100ms(void);
void core0_task_1s(void);

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/* Interrupt definition */
IFX_INTERRUPT (stm0Sr0ISR, 0, IFX_INTPRIO_STM0_SR0);

/* STM Initialization */
uint16 varResistorMeasurement = 0;
uint16 lightSensorMeasurement = 0;

void init_stm0(void)
{
    //IfxStm_enableOcdsSuspend(&MODULE_STM0);

    IfxCpu_disableInterrupts();

    stmSfr = &MODULE_STM0;
    IfxStm_initCompareConfig(&stmConfig);

    stmConfig.ticks = STM_TIME_1MS;

    stmConfig.triggerPriority = IFX_INTPRIO_STM0_SR0;
    stmConfig.typeOfService = IfxSrc_Tos_cpu0;

    IfxStm_initCompare(stmSfr, &stmConfig);

    IfxCpu_enableInterrupts();
}



void stm0Sr0ISR(void)
{
    IfxStm_clearCompareFlag(stmSfr, stmConfig.comparator);
    IfxStm_increaseCompare(stmSfr, stmConfig.comparator, stmConfig.ticks);

    taskCounter++;

    if((taskCounter % 1) == 0U)
    {
        task1msFlag = 1U;
    }

    if((taskCounter % 10) == 0U)
    {
        task10msFlag = 1U;
    }


    if((taskCounter % 100) == 0U)
    {
        task100msFlag = 1U;
    }

    if((taskCounter % 1000) == 0U)
    {
        task1sFlag = 1U;
    }
}

/* task */
void core0_task(void)
{
   if(task1msFlag == 1U)
   {
       task1msFlag = 0U;
       core0_task_1ms();
   }
   if(task10msFlag == 1U)
   {
       task10msFlag = 0U;
       core0_task_10ms();
   }
   if(task100msFlag == 1U)
   {
       task100msFlag = 0U;
       core0_task_100ms();
   }
   if(task100msFlag == 1U)
   {
       task100msFlag = 0U;
       core0_task_100ms();
   }
   if(task1sFlag == 1U)
   {
       task1sFlag = 0U;
       core0_task_1s();
   }
}

void core0_task_1ms(void)
{
    ;

}

void core0_task_10ms(void)
{
;
}

void core0_task_100ms(void)
{
    varResistorMeasurement= readADCValue(0);
    lightSensorMeasurement=readADCValue(1);


}

void core0_task_1s(void)
{
    ;
}

